// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// This is a placeholder - you should run `flutterfire configure` to generate
/// the correct options for your Firebase project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ9kePFarH4aIt67QE-pjxa7pAY98zQWs',
    appId: '1:484779982729:web:3fd098a13ca302efd02b58',
    messagingSenderId: '484779982729',
    projectId: 'tiroconnect-dev123',
    authDomain: 'tiroconnect-dev123.firebaseapp.com',
    storageBucket: 'tiroconnect-dev123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVHFOUlOPS6mVSvzrBKFzFI6rS681eFao',
    appId: '1:484779982729:android:ad82cfd2795845b5d02b58',
    messagingSenderId: '484779982729',
    projectId: 'tiroconnect-dev123',
    storageBucket: 'tiroconnect-dev123.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXzUvQGKPOsWtf-uTR3GwO-yNVr3bjv-U',
    appId: '1:484779982729:ios:d487246eea90e24dd02b58',
    messagingSenderId: '484779982729',
    projectId: 'tiroconnect-dev123',
    storageBucket: 'tiroconnect-dev123.firebasestorage.app',
    iosBundleId: 'com.example.tiroconnect',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXzUvQGKPOsWtf-uTR3GwO-yNVr3bjv-U',
    appId: '1:484779982729:ios:d487246eea90e24dd02b58',
    messagingSenderId: '484779982729',
    projectId: 'tiroconnect-dev123',
    storageBucket: 'tiroconnect-dev123.firebasestorage.app',
    iosBundleId: 'com.example.tiroconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ9kePFarH4aIt67QE-pjxa7pAY98zQWs',
    appId: '1:484779982729:web:1ea595d0b80eb8d6d02b58',
    messagingSenderId: '484779982729',
    projectId: 'tiroconnect-dev123',
    authDomain: 'tiroconnect-dev123.firebaseapp.com',
    storageBucket: 'tiroconnect-dev123.firebasestorage.app',
  );
}
